### ISSUE TITLE
"LLVM ERROR: inconsistency in registered CommandLine options" on Ubuntu when importing numba within QGIS

### ISSUE THREAD

**Issue by danschef** [conda-forge/numba-feedstock#75] opened 2021-03-17 12:54 UTC
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I am currently involved in the development of a QGIS plugin that uses numba under the hood and there seems to be a compatibility issue between numba and QGIS on Linux (at least on my Ubuntu 20.04 machine).

When installing qgis and numba from conda-forge into the same environment, qgis crashes when trying to import numba via the QGIS Python console. Here is a minimal environment that reproduces the issue:

`$ conda create -n qgisnumba -c conda-forge qgis numba`
<br/>
This installs the following environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/danschef/miniconda3/envs/qgisnumba:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
boost-cpp                 1.72.0               h9d3c048_4    conda-forge
brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.1.19            h06a4308_1
cairo                     1.16.0            h7979940_1007    conda-forge
certifi                   2020.12.5        py39hf3d152e_1    conda-forge
cffi                      1.14.5           py39he32792d_0    conda-forge
cfitsio                   3.470                hb418390_7    conda-forge
chardet                   4.0.0            py39hf3d152e_1    conda-forge
coverage                  5.5              py39h3811e60_0    conda-forge
cryptography              3.4.6            py39hbca0aa6_0    conda-forge
curl                      7.75.0               h979ede3_0    conda-forge
dbus                      1.13.18              hb2f20db_0
exiv2                     0.27.1               had08079_0    conda-forge
expat                     2.2.10               h9c3ff4c_0    conda-forge
fontconfig                2.13.1            hba837de_1004    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.6                h7f98852_0    conda-forge
future                    0.18.2           py39hf3d152e_3    conda-forge
gdal                      3.2.1            py39h409cc32_7    conda-forge
geos                      3.9.1                h9c3ff4c_2    conda-forge
geotiff                   1.6.0                h11d48b3_4    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.66.7               h9c3ff4c_1    conda-forge
glib-tools                2.66.7               h9c3ff4c_1    conda-forge
gsl                       2.6                  he838d99_2    conda-forge
gst-plugins-base          1.18.4               h29181c9_0    conda-forge
gstreamer                 1.18.4               h76c114f_0    conda-forge
hdf4                      4.2.13            h10796ff_1004    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
httplib2                  0.19.0             pyhd8ed1ab_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
jpeg                      9d                   h516909a_0    conda-forge
json-c                    0.15                 h98cffda_0    conda-forge
jsoncpp                   1.9.4                h4bd325d_1    conda-forge
kealib                    1.4.14               hcc255d8_2    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
laszip                    3.4.3                he1b5a44_1    conda-forge
laz-perf                  1.5.0                he1b5a44_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_0    conda-forge
libcurl                   7.75.0               hc4aaa36_0    conda-forge
libdap4                   3.20.6               hd7c4107_1    conda-forge
libedit                   3.1.20210216         h27cfd23_1
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_18    conda-forge
libgdal                   3.2.1                h38ff51b_7    conda-forge
libgfortran-ng            9.3.0               hff62375_18    conda-forge
libgfortran5              9.3.0               hff62375_18    conda-forge
libglib                   2.66.7               h3e27bee_1    conda-forge
libgomp                   9.3.0               h2828fa1_18    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             hd79254b_1012    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm10                 10.0.1               he513fc3_3    conda-forge
libllvm11                 11.1.0               hf817b99_0    conda-forge
libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libopenblas               0.3.12          pthreads_h4812303_1    conda-forge
libpng                    1.6.37               hed695b0_2    conda-forge
libpq                     13.1                 hfd2b0eb_2    conda-forge
libprotobuf               3.15.6               h780b84a_0    conda-forge
librttopo                 1.1.0                h1185371_6    conda-forge
libspatialindex           1.9.3                he1b5a44_3    conda-forge
libspatialite             5.0.1                he52d314_3    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_18    conda-forge
libtiff                   4.2.0                hdc55705_0    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.2.0                h3452ae3_0    conda-forge
libwebp-base              1.2.0                h7f98852_1    conda-forge
libxcb                    1.14                 h7b6447c_0
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.10               h72842e0_3    conda-forge
libxslt                   1.1.33               h15afd5d_2    conda-forge
libzip                    1.7.3                he9f05b3_0    conda-forge
llvmlite                  0.36.0           py39h1bbdace_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markupsafe                1.1.1            py39h3811e60_3    conda-forge
mock                      4.0.3            py39hf3d152e_1    conda-forge
mysql-common              8.0.23               ha770c72_1    conda-forge
mysql-libs                8.0.23               h935591d_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nitro                     2.7.dev6             he1b5a44_3    conda-forge
nose2                     0.9.2                      py_0    conda-forge
nspr                      4.30                 h9c3ff4c_0    conda-forge
nss                       3.62                 hb5efdd6_0    conda-forge
numba                     0.53.0           py39h4292f66_0    conda-forge
numpy                     1.20.1           py39hdbf815f_0    conda-forge
openjpeg                  2.4.0                hf7af979_0    conda-forge
openssl                   1.1.1j               h7f98852_0    conda-forge
owslib                    0.23.0             pyhd8ed1ab_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pdal                      2.2.0                h638e970_7    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
plotly                    4.14.3             pyh44b312d_0    conda-forge
poppler                   0.89.0               h2de54a5_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.1                 h6303168_2    conda-forge
proj                      7.2.0                h277dcde_2    conda-forge
psycopg2                  2.8.6            py39h3811e60_2    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.0.1            py39h50a64a9_0    conda-forge
pyqt                      5.12.3           py39hf3d152e_7    conda-forge
pyqt-impl                 5.12.3           py39h0fcd23e_7    conda-forge
pyqt5-sip                 4.19.18          py39he80948d_7    conda-forge
pyqtchart                 5.12             py39h0fcd23e_7    conda-forge
pyqtwebengine             5.12.1           py39h0fcd23e_7    conda-forge
pyqtwebkit                5.212            py39h20c28b1_1    conda-forge
pysocks                   1.7.1            py39hf3d152e_3    conda-forge
python                    3.9.2           hffdb5ce_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.9                      1_cp39    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py39h3811e60_0    conda-forge
qca                       2.2.1                h73816c6_3    conda-forge
qgis                      3.18.0           py39hce95e4c_3    conda-forge
qjson                     0.9.0             h73816c6_1006    conda-forge
qscintilla2               2.11.2           py39hf01f197_4    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
qtkeychain                0.12.0               h2264404_0    conda-forge
qtlocation                5.12.9               he1b5a44_0    conda-forge
qtserialport              5.9.8                h73816c6_1    conda-forge
qtwebkit                  5.212                h8f65c2e_1    conda-forge
qwt                       6.1.6                h7ec6b3e_0    conda-forge
qwtpolar                  1.1.1                h73816c6_7    conda-forge
readline                  8.1                  h27cfd23_0
requests                  2.25.1             pyhd3deb0d_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
setuptools                52.0.0           py39h06a4308_0
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.35.1               hdfb4753_0
tiledb                    2.2.4                h91fcb0e_3    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
tzcode                    2021a                h7f98852_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xerces-c                  3.2.3                h9d8b166_2    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.0                h36c2ea0_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
```
</details>

QGIS can than be started by running `qgis` on the command line and everything works fine. However, as soon as I open a Python console within QGIS and import numba, QGIS crashes and raises the following error at the command line:
```
(qgisnumba) gfz-fe@geoms:~$ qgis
Warning: QXcbConnection: XCB error: 145 (Unknown), sequence: 179, resource id: 0, major code: 139 (Unknown), minor code: 20
: CommandLine Error: Option 'help-list' registered more than once!
LLVM ERROR: inconsistency in registered CommandLine options
QGIS died on signal 11Aborted
```

To me, this looks like there is something wrong with the LLVM link in the numba recipe. That´s why I open the issue here and not in the qgis-feedstock.

Note that when I start a Python console directly on the command line (without QGIS), I can import qgis and numba without any issues. So the error only occurs when numba is imported from the QGIS command line (or by a QGIS plugin which uses numba). We also tested this with the same environment on Windows, without any issues.

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
(qgisnumba) gfz-fe@geoms:~$ conda info

     active environment : qgisnumba
    active env location : /home/danschef/miniconda3/envs/qgisnumba
            shell level : 4
       user config file : /home/danschef/.condarc
 populated config files : /home/danschef/.condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/danschef/miniconda3  (writable)
           channel URLs : file:///home/danschef/.conda_channels_local/pygfz/linux-64
                          file:///home/danschef/.conda_channels_local/pygfz/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/danschef/miniconda3/pkgs
                          /home/danschef/.conda/pkgs
       envs directories : /home/danschef/miniconda3/envs
                          /home/danschef/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.8 Linux/5.4.0-52-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 1009:38755
             netrc file : None
           offline mode : False

```
</details>

**Comment by henryiii** [comment] 2021-03-17 14:09
A similar problem with a discussion here: https://github.com/CastXML/CastXML/issues/102

**Comment by henryiii** [comment] 2021-03-18 04:42
Though I'd expect this is at least an issue for llvmlite, not numba?

**Comment by danschef** [comment] 2021-03-23 17:45
Ok, I just assumed that it might be caused by the numba recipe, e.g., by the pinned LLVM version [here](https://github.com/conda-forge/numba-feedstock/blob/aa5136c2f2b2f809f33f80650377bbf38ef4f8bc/recipe/meta.yaml#L40). But don´t know enough about how numba is linked to LLVM..

Maybe the llvmlite-feedstock maintainers can help? 
@jakirkham @marcelotrevisani @mbargull @souravsingh @xhochy

**Comment by chrisburr** [comment] 2021-04-23 08:49
This was caused by a known mesa bug which conda-forge can't do anything so I'll close this. For more details see https://github.com/conda-forge/llvmlite-feedstock/issues/54.

**Closed by chrisburr** 2021-04-23 08:49 UTC
